### ISSUE TITLE
cannot start route server

### ISSUE THREAD

**Issue by hongmou** [wenjian0202/amod-abm#3]
After I ran` ./osrm-backend-5.11.0/build/osrm-routed boston_massachusetts.osm.pbf`
I got
```
[warn] Missing/Broken File: boston_massachusetts.osrm.datasource_names
[error] Required files are missing, cannot continue
```

**Comment by wenjian0202** [comment]
yeah this helps to remind everyone:
when using a new map, make sure the map path, in line 15 of `main.py`, is good.
 e.g. `map_loc = './osrm-backend-5.11.0/boston_massachusetts.osm.pbf'`
